[package]
name = "scheduling"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "scheduling"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
erlang_nif-sys = "0.6.4"
rustler = "0.20.0"
